name: Integrative Bodybuilding - Home of Fortitude Training
favicon: null
layout_spectrum: 0.2967304780613631
typography_spectrum: 0.0012322296388447285
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.09092316217720509
  lightness: 0.14127599401399493
  saturation: 0.04864448122680187
  rhythmicContrast: 0.8334529125131667
purpose: []
